# Generated by Django 4.2.20 on 2025-05-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('speed', models.FloatField()),
                ('armor_thickness', models.FloatField()),
                ('firepower', models.FloatField()),
            ],
        ),
    ]
