# Generated by Django 4.2.20 on 2025-05-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army', '0002_equipment_alter_tank_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tank',
            old_name='speed',
            new_name='speed_in_kilometer_per_hours',
        ),
        migrations.RenameField(
            model_name='tank',
            old_name='weight',
            new_name='weight_in_tonnes',
        ),
        migrations.AlterField(
            model_name='tank',
            name='armor_thickness',
            field=models.TextField(max_length=300),
        ),
    ]
