# Generated by Django 4.2.20 on 2025-05-09 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('army', '0003_rename_speed_tank_speed_in_kilometer_per_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tank',
            old_name='speed_in_kilometer_per_hours',
            new_name='speed_in_kmph',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='weight_in_tonnes',
        ),
        migrations.AddField(
            model_name='tank',
            name='weight',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tank',
            name='armor_thickness',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tank',
            name='firepower',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tank',
            name='name',
            field=models.TextField(),
        ),
    ]
